
name: "Setup mac environment"
description: "Loads the environment variables to be used in the workflows"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "cache"
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.81

    - name: Install Ubuntu deps
      run: |
        sudo apt-get update
        sudo apt-get install -y netcat-openbsd

    - name: Build cli
      run: cargo build