name: Task - Appchain Linux

on:
  workflow_dispatch:
  workflow_call:

jobs:
  appchain_linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup app chain and run tests
        run: |
          cargo build
          cargo run -p madara create app-chain &
          MADARA_PID=$!
          until [ "$(docker inspect -f '{{.State.Running}}' bootstrapper_l2 2>/dev/null)" = "true" ]; do
            echo "Waiting for Bootstrapper L2 container to start..."
            sleep 1
          done
          echo "Waiting for Bootstrapper L2 container to finish..."
          docker wait bootstrapper_l2
          echo "Running transfer scripts..."
          cd deps/scripts/transfer_from_L1
          npm install
          npm run transfer-l1
          kill $MADARA_PID
