name: Task - Validate commands

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81
      - name: Build cli
        run: cargo build
      - name: Check devnet
        run: cargo run -p madara create devnet
      - name: Check sequencer
        run: cargo run -p madara create sequencer --preset-type sepolia
      - name: Check full-node
        run: cargo run -p madara create full-node --network devnet
