name: Task - Devnet Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  devnet_test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - uses: ./.github/actions/setup-linux

      - name: Setup dev chain and run tests
        run: |
          cargo run -p madara create devnet &
          MADARA_PID=$!
          echo "$RUNNER_OS pinging"
          while ! echo exit | nc localhost 9944; do sleep 1; done
          kill $MADARA_PID
