name: "Docker Images"
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'The name of the image to build (e.g., madara, orchestrator, bootstrapper)'
        required: true
        default: 'madara'
      organization:
        description: 'The Docker Hub organization to publish to'
        required: true
        default: 'ftheirs'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set image name from input
        id: image_name
        run: echo "name=${{ github.event.inputs.image_name }}" >> $GITHUB_OUTPUT
      
      - name: Set organization name
        id: org_name
        run: echo "org=${{ github.event.inputs.organization }}" >> $GITHUB_OUTPUT
      
      - name: Git commit hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: deps/${{ steps.image_name.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.org_name.outputs.org }}/${{ steps.image_name.outputs.name }}:${{ steps.hash.outputs.hash }},${{ steps.org_name.outputs.org }}/${{ steps.image_name.outputs.name }}:latest