name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  rust_check:
    name: Run check
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/rust-check.yml

  devnet:
    name: Run test
    needs: rust_check
    uses: ./.github/workflows/devnet-test.yml

  # build:
  #   name: Build Madara
  #   needs: update_db_version
  #   uses: ./.github/workflows/build.yml

  # js_test:
  #   name: Run JS Tests
  #   needs: build
  #   uses: ./.github/workflows/starknet-js-test.yml
