---
name: Task - Run Cargo tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run unit tests
        run: |
          cargo test --workspace
